use_frameworks!

platform :ios, '10.0'

target 'ScanLib_Example' do
  pod 'ScanLib', :path => '../'

  target 'ScanLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
